version: '3.7'
name: mocker-db
services:
  dynamodb:
    image:  amazon/dynamodb-local
    container_name: pagopamockresources
    hostname: pagopamockdb
    restart: always
    volumes:
      - ../dist/pagopamockdb-data:/home/dynamodblocal/data
    ports:
      - 8000:8000
    networks:
      dynamodbNetwork:
        ipv4_address: 172.22.0.2
        aliases:
        - dynamodblocal
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"
    
networks:
  dynamodbNetwork:
    name: dynamo_net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.22.0.2/16"